apiVersion: v1
kind: Service
metadata:
  name: vproapp-nodeport
spec:
  type: NodePort
  selector:
    app: vproapp
  ports:
  - port: 80
    targetPort: vproapp-port
    nodePort: 30001
    protocol: TCP
